apiVersion: v2
name: mealie
description: Mealie is a self hosted recipe manager and meal planner with a RestAPI backend and a reactive frontend application built in Vue for a pleasant user experience for the whole family.
version: 1.0.4
appVersion: "v2.5.0"
kubeVersion: ">=1.16.0-0"
keywords:
  - mealie
sources:
  - https://github.com/mealie-recipes/mealie
dependencies:
  - name: postgresql
    version:  16.3.5
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
maintainers:
  - name: Douwe Meulenbroek
    # email: your-email@example.com    