apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-cleanup-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-cleanup-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvc-cleanup-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: pvc-cleanup
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pvc-cleanup-role
  apiGroup: rbac.authorization.k8s.io
