apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-dump-restore
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pg-dump-restore-role
  namespace: {{ .Release.Namespace }}
rules:
  # Basic pod access for exec and control
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create", "delete", "patch"]
  
  # Permissions to scale Deployments
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "patch", "update"]

  # Permissions to scale StatefulSets
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["get", "list", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pg-dump-restore-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pg-dump-restore-role
subjects:
  - kind: ServiceAccount
    name: pg-dump-restore
    namespace: {{ .Release.Namespace }}
