{{- if .Values.postgresql.upgrade.database }}
apiVersion: batch/v1
kind: Job
metadata:
  name: scale-up-mealie
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "18"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: pg-dump-restore
      restartPolicy: Never
      containers:
        - name: scale-up
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "🔻 Scaling up Mealie..."
              kubectl scale deploy mealie-webservice -n {{ .Release.Namespace }} --replicas=1
{{- end }}
