{{- if .Values.postgresql.upgrade.database }}
apiVersion: batch/v1
kind: Job
metadata:
  name: scale-down-mealie
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: pg-dump-restore
      restartPolicy: Never
      containers:
      - name: scale-down
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "🔻 Scaling down Mealie deployment to 0 replicas..."
            kubectl scale deployment mealie-webservice --replicas=0 -n {{ .Release.Namespace }}
{{- end }}
