{{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) (or .Values.smtp.user .Values.smtp.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-smtp" .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.smtp.user }}
  {{ .Values.smtp.secretKeys.user | default "SMTP_USER" }}: {{ .Values.smtp.user | quote }}
  {{- end }}
  {{- if .Values.smtp.password }}
  {{ .Values.smtp.secretKeys.password | default "SMTP_PASSWORD" }}: {{ .Values.smtp.password | quote }}
  {{- end }}
{{- end }}