# templates/oidc-secret.yaml
{{- if and .Values.oidc.enabled (not .Values.oidc.existingSecret) .Values.oidc.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-oidc" .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.oidc.secretKeys.clientSecretKey | default "OIDC_CLIENT_SECRET" }}: {{ .Values.oidc.clientSecret | quote }}
{{- end }}