# templates/ldap-secret.yaml
{{- if and .Values.ldap.enabled (not .Values.ldap.existingSecret) .Values.ldap.queryPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ldap" .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.ldap.secretKeys.queryPassword | default "LDAP_QUERY_PASSWORD" }}: {{ .Values.ldap.queryPassword | quote }}
{{- end }}