---
{{- if and .Values.ingress.traefik.enabled (not .Values.ingress.nginx.enabled ) }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.traefik.ingressClass | quote }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.config.base_url }}`)
      kind: Rule
      services:
        - name: {{ .Values.service.name | quote }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: default-headers
          namespace: {{ .Release.namespace }}

    - match: "Host(`{{ .Values.config.base_url }}`) && PathPrefix(`/admin`)"
      kind: Rule
      services:
        - name: {{ .Values.service.name | quote }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: mealie-adminpage
          namespace: {{ .Release.namespace }}
        - name: default-headers
          namespace: {{ .Release.namespace }}

    - match:  "Host(`{{ .Values.config.base_url }}`) && PathPrefix(`/docs`)"
      kind: Rule
      services:
        - name: {{ .Values.service.name | quote }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: mealie-adminpage
          namespace: {{ .Release.namespace }}        
        - name: default-headers
          namespace: {{ .Release.namespace }}        

#For security reasons
    - match: "Host(`{{ .Values.config.base_url }}`) && PathPrefix(`/api/recipes/create/url`)"
      kind: Rule
      services:
        - name: {{ .Values.service.name | quote }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: mealie-ratelimit
          namespace: {{ .Release.namespace }}        
        - name: default-headers
          namespace: {{ .Release.namespace }}        

#For security reasons
    - match: "Host(`{{ .Values.config.base_url }}`) && PathPrefix(`/api/recipes/{id}/image`)"
      kind: Rule
      services:
        - name: {{ .Values.service.name | quote }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: mealie-ratelimit
          namespace: {{ .Release.namespace }} 
  tls:
    secretName: "kokenmetdouwe-nl-tls"
    options:
      name: {{ .Values.ingress.traefik.tls.options | quote}}
      namespace: {{ .Release.Namespace }}
{{- end }}