{{ if .Values.smtp.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-smtp-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Database connection URL encoded in base64
  SMTP_HOST: {{ .Values.smtp.host | b64enc }}
  SMTP_USER: {{ .Values.smtp.user | b64enc }}
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc }}
{{- end }}
