
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-postgres-server-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgres-server: {{ printf "%s-postgresql.%s.svc.cluster.local" .Release.Name  .Release.Namespace | b64enc }}
{{- end }}
