---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: mealie-api-data-claim-{{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
