{{- $pvc := lookup "v1" "PersistentVolumeClaim" .Release.Namespace (printf "mealie-api-data-claim-%s" .Release.Namespace) }}
{{- if not $pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: mealie-api-data-claim-{{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- else }}
# PVC already exists, skipping creation
{{- end }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: mealie-api-data-claim-{{ .Release.Namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}

---
{{- if .Values.postgresql.upgrade.temp_storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backup-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
