---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace}}
  name: mealie-api-data-claim
spec:
  storageClassName: {{ .Values.persistance.storageClassName }}
  accessModes:
    - {{ .Values.persistance.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistance.size }}
